# Token Usuario
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWE4YzAwYTgzYmY3NjQyYzA0OTRkZCIsImVtYWlsIjoidXN1YXJpb0B1c3VhcmlvLmNvbSIsInRpcG8iOiJ1c3VhcmlvIiwiaWF0IjoxNzEzMDE1ODEzLCJleHAiOjE3MTMxMDIyMTN9.tWkHub16bOWjhZ-3tD_tNbBJXh8_vhwk5Eve8BCoJls

# Token Admin
#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWE3YTk4ZDZmMzgwMjRlODkyOGYyNSIsImVtYWlsIjoiYWRyaWFuLnRvcmFsQGxpdmUudS10YWQuY29tIiwidGlwbyI6InVzdWFyaW8iLCJpYXQiOjE3MTMwMTYwMTAsImV4cCI6MTcxMzEwMjQxMH0.YNuI6Q2WeR3pMbWN6_1VSIlgaSpq_w3ocos3IMQBHXY

### /api/v1/comercios
GET http://localhost:3000/api/v1/comercios

### /api/v1/comercios?sortBy=cif
GET http://localhost:3000/api/v1/comercios?sortBy=cif

### /api/v1/comercios/:param
GET http://localhost:3000/api/v1/comercios/MICIF12345

### /api/v1/comercios
POST http://localhost:3000/api/v1/comercios
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Mi Comercio",
  "cif": "MICIF12345",
  "direccion": "Calle Falsa 123",
  "email": "adrian.toral@live.u-tad.com",
  "telefono": "+34123456789"
}

### /api/v1/comercios/:param
PUT http://localhost:3000/api/v1/comercios/MICIF12345
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Mi Comercio mejorado",
  "direccion": "Calle Falsa 123",
  "email": "adrian.toral@live.u-tad.com",
  "telefono": "+34123456789"
}

### /api/v1/comercios/:param
PATCH http://localhost:3000/api/v1/comercios/MICIF12345
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Mi Comercio mejorado",
  "email": "adrian.toral@live.u-tad.com"
}

### /api/v1/comercios/:param (logico)
DELETE http://localhost:3000/api/v1/comercios/MICIF12345?logico=true
Authorization: Bearer {{token}}

### /api/v1/comercios/:param (fisico)
DELETE http://localhost:3000/api/v1/comercios/MICIF12345
Authorization: Bearer {{token}}
Content-Type: application/json
