# Token Comercio
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWE4ZDhiYTgzYmY3NjQyYzA0OTRmNyIsImNpZiI6Ik1JQ0lGMTIzNDUiLCJ0aXBvIjoiY29tZXJjaW8iLCJpYXQiOjE3MTMwMTYyMDN9.NhkU1MKbt5zKOXTUWRoLINqFcC5Fn-JknadwyA2ljE0

# Token Usuario
#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MWE4YzAwYTgzYmY3NjQyYzA0OTRkZCIsImVtYWlsIjoidXN1YXJpb0B1c3VhcmlvLmNvbSIsInRpcG8iOiJ1c3VhcmlvIiwiaWF0IjoxNzEzMDE1ODEzLCJleHAiOjE3MTMxMDIyMTN9.tWkHub16bOWjhZ-3tD_tNbBJXh8_vhwk5Eve8BCoJls

### /api/v1/webs
GET http://localhost:3000/api/v1/webs

### /api/v1/webs?sortBy=cif
GET http://localhost:3000/api/v1/webs?sortBy=ciudad

### /api/v1/webs/:param
GET http://localhost:3000/api/v1/webs/661a7b3705f8c0fa0ea62aa4

### /api/v1/webs/ciudad/:param
GET http://localhost:3000/api/v1/webs/ciudad/Madrid

### /api/v1/webs/ciudad/:param/:param2
GET http://localhost:3000/api/v1/webs/ciudad/Madrid/Teconologia

### /api/v1/webs
POST http://localhost:3000/api/v1/webs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ciudad": "Madrid",
  "actividad": "Teconologia",
  "titulo": "Telefonica",
  "resumen": "Telefonica es una empresa de telecomunicaciones",
  "textos": [
    "Telefonica es una empresa de telecomunicaciones",
    "Telefonica es una empresa de telecomunicaciones"
  ],
  "fotos": [
    "https://www.telefonica.com/es/web/guest/home",
    "https://www.telefonica.com/es/web/guest/home"
  ]
}

### /api/v1/webs
PUT http://localhost:3000/api/v1/webs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ciudad": "Madrid",
  "actividad": "Teconologia Mejorada",
  "titulo": "Telefonica",
  "resumen": "Telefonica es una empresa de telecomunicaciones",
  "textos": [
    "Telefonica es una empresa de telecomunicaciones",
    "Telefonica es una empresa de telecomunicaciones"
  ],
  "fotos": [
    "https://www.telefonica.com/es/web/guest/home",
    "https://www.telefonica.com/es/web/guest/home"
  ]
}

### /api/v1/webs
PATCH http://localhost:3000/api/v1/webs
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ciudad": "Barcelona",
  "titulo": "Telefonica Mejorada"
}

### /api/v1/webs?logico=true (logico)
DELETE http://localhost:3000/api/v1/webs?logico=true
Authorization: Bearer {{token}}

### /api/v1/webs (fisico)
DELETE http://localhost:3000/api/v1/webs
Authorization: Bearer {{token}}
